// apps/mvvm-react-integrated/src/components/ThresholdAlertCard.tsx
import type { ThresholdAlertListData } from '@repo/view-models/ThresholdAlertViewModel';
import React from 'react';
import { Link } from 'react-router-dom';

interface ThresholdAlertCardProps {
  thresholdAlerts: ThresholdAlertListData;
}

const ThresholdAlertCard: React.FC<ThresholdAlertCardProps> = ({ thresholdAlerts }) => {
  return (
    <div className="card">
      <Link to="/threshold-alerts" className="card-header-link">
        <h3 className="card-title">Alerts</h3>
      </Link>
      <p className="card-content">Total Alerts: {thresholdAlerts.length}</p>
    </div>
  );
};

export default ThresholdAlertCard;

// apps/mvvm-lit/src/components/threshold-alert-card.ts
import { LitElement, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { thresholdAlertViewModel, type ThresholdAlertListData } from '@repo/view-models/ThresholdAlertViewModel';
import { Subscription } from 'rxjs';

@customElement('threshold-alert-card')
export class ThresholdAlertCard extends LitElement {
  createRenderRoot() {
    return this;
  }
  @state() private thresholdAlerts: ThresholdAlertListData = [];
  private subscription: Subscription | null = null;

  connectedCallback() {
    super.connectedCallback();
    this.subscription = thresholdAlertViewModel.data$.subscribe((data: any) => {
      this.thresholdAlerts = data;
    });
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.subscription?.unsubscribe();
  }

  render() {
    return html`
      <div class="card">
        <h3 class="card-title">
          <a href="/threshold-alerts" class="card-title-link">Threshold Alerts</a>
        </h3>
        <p class="card-content">Total: ${this.thresholdAlerts.length}</p>
      </div>
    `;
  }
}
