// apps/mv-lit/src/components/threshold-alert-list.ts
import { LitElement, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { thresholdAlertViewModel, ThresholdAlertData } from '@repo/view-models/ThresholdAlertViewModel';
import { Subscription } from 'rxjs';

@customElement('threshold-alert-list')
export class ThresholdAlertList extends LitElement {
  @state() private thresholdAlerts: ThresholdAlertData[] = [];
  private subscription: Subscription | null = null;

  connectedCallback() {
    super.connectedCallback();
    this.subscription = thresholdAlertViewModel.data$.subscribe(data => {
      this.thresholdAlerts = data;
    });
    thresholdAlertViewModel.fetchCommand.execute();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.subscription?.unsubscribe();
  }

  render() {
    return html`
      <a href="/" class="back-button">
        <img src="/back-arrow.svg" alt="Back to dashboard" style="width: 36px; height: 36px" />
      </a>
      <div class="card">
        <h1 class="card-title">Threshold Alerts</h1>
        ${this.thresholdAlerts && this.thresholdAlerts.length > 0
          ? html`
              <ul class="card-content list">
                ${this.thresholdAlerts.map(
                  (alert) =>
                    html`<li class="list-item">
                      Alert ID: ${alert.id}, Sensor ID: ${alert.sensorType}, Message: Max: ${alert.maxValue}, Min: ${alert.minValue}
                    </li>`,
                )}
              </ul>
            `
          : html`<p>No threshold alerts found or still loading...</p>`}
      </div>
    `;
  }
}

// apps/mvvm-react/src/components/ThresholdAlertList.tsx
import { useEffect } from 'react';
import { thresholdAlertViewModel } from '@repo/view-models/ThresholdAlertViewModel';
import { useSignal } from '../hooks/useSignal';
import BackArrow from '../assets/back-arrow.svg';
import { Link } from 'react-router-dom';

export function ThresholdAlertList() {
  const thresholds = useSignal(thresholdAlertViewModel.data$);

  useEffect(() => {
    const fetchData = async () => {
      await thresholdAlertViewModel.fetchCommand.execute();
    };
    fetchData();
  }, []);

  return (
    <>
      <Link to="/" className="back-button">
        <img src={BackArrow} alt="Back to dashboard" style={{ width: '36px', height: '36px' }} />
      </Link>
      <div className="card">
        <h1 className="card-title">Threshold Alerts</h1>
        {thresholds && thresholds.length > 0 ? (
          <ul className="card-content list">
            {thresholds.map((alert) => (
              <li key={alert.id} className="list-item">
                Alert ID: {alert.id}, Sensor ID: {alert.sensorType}, Message: Max: {alert.maxValue}, Min:{' '}
                {alert.minValue}
              </li>
            ))}
          </ul>
        ) : (
          <p>No threshold alerts found or still loading...</p>
        )}
      </div>
    </>
  );
}
