// apps/mvvm-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import '@repo/shared/styles';
import { HeaderComponent } from './layout/header/header.component';
import { FooterComponent } from './layout/footer/footer.component';
import { ContainerComponent } from './layout/container/container.component';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, HeaderComponent, FooterComponent, ContainerComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  title = 'Angular MVVM';
}

<app-header></app-header>
<app-container>
  <router-outlet />
</app-container>
<app-footer></app-footer>

// apps/plugin-react/src/App.tsx
import '@repo/shared/styles';
import './App.css';
import { BrowserRouter } from './router/Routing';
import { Header } from './layout/Header';
import Container from './layout/Container';
import Footer from './layout/Footer';
import { PluginHost, PluginHostProvider } from './host/PluginHost';

function App() {
  return (
    <BrowserRouter>
      <PluginHostProvider>
        <Header />
        <Container>
          <PluginHost />
        </Container>
        <Footer />
      </PluginHostProvider>
    </BrowserRouter>
  );
}

export default App;
