// apps/mvvm-vue/src/App.vue
<template>
  <div id="app">
    <Header />
    <Container>
      <router-view />
    </Container>
    <Footer />
  </div>
</template>
<script setup lang="ts">
import Header from './layout/Header.vue';
import Footer from './layout/Footer.vue';
import Container from './layout/Container.vue';
</script>

<style scoped></style>

// apps/plugin-react/src/App.tsx
import '@repo/shared/styles';
import './App.css';
import { BrowserRouter } from './router/Routing';
import { Header } from './layout/Header';
import Container from './layout/Container';
import Footer from './layout/Footer';
import { PluginHost, PluginHostProvider } from './host/PluginHost';

function App() {
  return (
    <BrowserRouter>
      <PluginHostProvider>
        <Header />
        <Container>
          <PluginHost />
        </Container>
        <Footer />
      </PluginHostProvider>
    </BrowserRouter>
  );
}

export default App;
