// apps/mvvm-lit/src/components/sensor-list.ts
import { LitElement, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { sensorViewModel, SensorListData } from '@repo/view-models/SensorViewModel';
import { Subscription } from 'rxjs';

@customElement('sensor-list')
export class SensorList extends LitElement {
  @state() private sensors: SensorListData = [];
  private subscription: Subscription | null = null;

  connectedCallback() {
    super.connectedCallback();
    this.subscription = sensorViewModel.data$.subscribe((data: any) => {
      this.sensors = data;
    });
    sensorViewModel.fetchCommand.execute();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.subscription?.unsubscribe();
  }

  render() {
    return html`
      <a href="/" class="back-button">
        <img src="/back-arrow.svg" alt="Back to dashboard" style="width: 36px; height: 36px" />
      </a>
      <div class="card">
        <h1 class="card-title">Sensors</h1>
        ${this.sensors && this.sensors.length > 0
          ? html`
              <ul class="card-content list">
                ${this.sensors.map(
                  (sensor: any) =>
                    html`<li class="list-item">
                      ${sensor.greenhouse.name} ${sensor.type} (Status: ${sensor.status})
                    </li>`,
                )}
              </ul>
            `
          : html`<p>No sensors found or still loading...</p>`}
      </div>
    `;
  }
}

// apps/plugin-react/src/components/SensorList.tsx
import { useEffect } from 'react';
import { sensorViewModel } from '@repo/view-models/SensorViewModel';
import { useObservable } from '../hooks/useObservable';
import { Link } from '../router/Routing';
import BackArrow from '../assets/back-arrow.svg';

export function SensorList() {
  const sensors = useObservable(sensorViewModel.data$, []);

  useEffect(() => {
    const fetchData = async () => {
      await sensorViewModel.fetchCommand.execute();
    };
    fetchData();
  }, []);

  return (
    <>
      <Link to="/" className="back-button">
        <img src={BackArrow} alt="Back to dashboard" style={{ width: '36px', height: '36px' }} />
      </Link>
      <div className="card">
        <h1 className="card-title">Sensors</h1>
        {sensors && sensors.length > 0 ? (
          <ul className="card-content list">
            {sensors.map((sensor) => (
              <li key={sensor.id} className="list-item">
                {sensor.greenhouse.name} {sensor.type} (Status: {sensor.status})
              </li>
            ))}
          </ul>
        ) : (
          <p>No sensors found or still loading...</p>
        )}
      </div>
    </>
  );
}
