// apps/mvvm-vue/src/components/ThresholdAlertCard.vue
<template>
  <div class="card">
    <router-link
      to="/threshold-alerts"
      class="card-header-link"
    >
      <h3 class="card-title">
        Alerts
      </h3>
    </router-link>
    <p
      v-if="thresholdAlertsProp"
      class="card-content"
    >
      Total Alerts: {{ thresholdAlertsProp.length }}
    </p>
    <p
      v-else
      class="card-content"
    >
      Total Alerts: 0
    </p>
  </div>
</template>

<script setup lang="ts">
import { defineProps } from 'vue';
import type { ThresholdAlertListData } from '@repo/view-models/ThresholdAlertViewModel';

defineProps<{
  thresholdAlertsProp?: ThresholdAlertListData | null;
}>();
</script>

<style scoped></style>

// apps/plugin-react/src/components/ThresholdAlertCard.tsx
import type { ThresholdAlertListData } from '@repo/view-models/ThresholdAlertViewModel';
import React from 'react';
import { Link } from '../router/Routing';

interface ThresholdAlertCardProps {
  thresholdAlerts: ThresholdAlertListData;
}

const ThresholdAlertCard: React.FC<ThresholdAlertCardProps> = ({ thresholdAlerts }) => {
  return (
    <div className="card">
      <Link to="/threshold-alerts" className="card-header-link">
        <h3 className="class-title">Alerts</h3>
      </Link>
      <p className="card-content">Total Alerts: {thresholdAlerts.length}</p>
    </div>
  );
};

export default ThresholdAlertCard;
