// packages/create-web-loom/src/templates/solid/js/src/hooks/useObservable.js
import { createSignal, onCleanup } from 'solid-js';

export function useSignalValue(signal) {
  const [value, setValue] = createSignal(signal.get());

  const sync = () => {
    setValue(signal.get());
  };

  sync();
  const unsubscribe = signal.subscribe(sync);
  onCleanup(unsubscribe);

  return value;
}

// packages/create-web-loom/src/templates/react/js/src/hooks/useObservable.js
import { useEffect, useState } from 'react';

export function useSignal(signal) {
  const [value, setValue] = useState(() => signal.get());

  useEffect(() => {
    const sync = () => {
      setValue(signal.get());
    };

    sync();
    return signal.subscribe(sync);
  }, [signal]);

  return value;
}
