// packages/create-web-loom/src/templates/solid/ts/src/hooks/useObservable.ts
import { createSignal, onCleanup } from 'solid-js';

type SignalLike<T> = {
  get: () => T;
  subscribe: (fn: () => void) => () => void;
};

export function useSignalValue<T>(signal: SignalLike<T>) {
  const [value, setValue] = createSignal(signal.get());

  const sync = () => {
    setValue(signal.get());
  };

  sync();
  const unsubscribe = signal.subscribe(sync);
  onCleanup(unsubscribe);

  return value;
}

// packages/create-web-loom/src/templates/react/ts/src/hooks/useObservable.ts
import { useEffect, useState } from 'react';

type SignalLike<T> = {
  get: () => T;
  subscribe: (fn: () => void) => () => void;
};

export function useSignal<T>(signal: SignalLike<T>): T {
  const [value, setValue] = useState<T>(() => signal.get());

  useEffect(() => {
    const sync = () => {
      setValue(signal.get());
    };

    sync();
    return signal.subscribe(sync);
  }, [signal]);

  return value;
}
