// packages/mvvm-core/examples/vue-example/src/components/TodoList.vue
<template>
  <div class="todo-list">
    <TodoListItem v-for="todo in todos" :key="todo.id" :todo="todo" :viewModel="viewModel" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, defineProps } from 'vue';
import type { Subscription } from 'rxjs';
import type { TodoListViewModel, TodoItem } from '@web-loom/mvvm-core';
import TodoListItem from './TodoListItem.vue';

const props = defineProps<{
  viewModel: TodoListViewModel;
}>();

const todos = ref<TodoItem[]>(props.viewModel.todos.toArray());
let todosSubscription: Subscription | null = null;

onMounted(() => {
  todosSubscription = props.viewModel.todos.items$.subscribe((updatedTodos) => {
    todos.value = updatedTodos;
  });
});

onUnmounted(() => {
  todosSubscription?.unsubscribe();
});
</script>

<style scoped>
.todo-list {
  margin-top: 1em;
}
</style>

// packages/mvvm-core/examples/react-example/src/components/TodoList.tsx
import React, { useState, useEffect } from 'react';
import { TodoListViewModel, TodoItem } from '@web-loom/mvvm-core';
import { TodoListItem } from './TodoListItem';

interface TodoListProps {
  viewModel: TodoListViewModel;
}

export const TodoList: React.FC<TodoListProps> = ({ viewModel }) => {
  const [todos, setTodos] = useState<TodoItem[]>(viewModel.todos.toArray());

  useEffect(() => {
    const todosSubscription = viewModel.todos.items$.subscribe((updatedTodos) => {
      setTodos(updatedTodos);
    });

    return () => {
      todosSubscription.unsubscribe();
    };
  }, [viewModel]);

  return (
    <div>
      {todos.map((todo) => (
        <TodoListItem key={todo.id} todo={todo} viewModel={viewModel} />
      ))}
    </div>
  );
};
