// packages/mvvm-core/examples/vue-example/src/components/TodoListItem.vue
<template>
  <div v-if="itemData" class="todo-list-item">
    <input type="checkbox" :checked="itemData.isCompleted" @change="handleToggle" />
    <span :class="{ completed: itemData.isCompleted }">
      {{ itemData.text }}
    </span>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, defineProps } from 'vue';
import type { Subscription } from 'rxjs';
import type { TodoItem, TodoItemData, TodoListViewModel } from '@web-loom/mvvm-core';

const props = defineProps<{
  todo: TodoItem;
  viewModel: TodoListViewModel;
}>();

const itemData = ref<TodoItemData | null>(null);
let dataSubscription: Subscription | null = null;

onMounted(() => {
  dataSubscription = props.todo.data$.subscribe((data) => {
    itemData.value = data;
  });
});

onUnmounted(() => {
  dataSubscription?.unsubscribe();
});

const handleToggle = () => {
  if (itemData.value) {
    props.viewModel.toggleTodoCommand.execute(itemData.value.id);
  }
};
</script>

<style scoped>
.todo-list-item {
  display: flex;
  align-items: center;
  padding: 0.5em 0;
  border-bottom: 1px solid #eee;
}
.todo-list-item:last-child {
  border-bottom: none;
}
input[type='checkbox'] {
  margin-right: 0.75em;
}
.completed {
  text-decoration: line-through;
  color: #aaa;
}
</style>

// packages/mvvm-core/examples/react-example/src/components/TodoListItem.tsx
import React, { useState, useEffect } from 'react';
import { TodoListViewModel, TodoItem, TodoItemData } from '@web-loom/mvvm-core';

interface TodoListItemProps {
  todo: TodoItem;
  viewModel: TodoListViewModel;
}

export const TodoListItem: React.FC<TodoListItemProps> = ({ todo, viewModel }) => {
  const [itemData, setItemData] = useState<TodoItemData | null>(null);

  useEffect(() => {
    const dataSubscription = todo.data$.subscribe((data) => {
      setItemData(data);
    });

    return () => {
      dataSubscription.unsubscribe();
    };
  }, [todo]);

  const handleToggle = () => {
    if (itemData) {
      viewModel.toggleTodoCommand.execute(itemData.id);
    }
  };

  if (!itemData) {
    return null;
  }

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        margin: '1em',
        padding: '0.5em 0',
        borderBottom: '1px solid #eee',
        borderRadius: '4px',
      }}
    >
      <input type="checkbox" checked={itemData.isCompleted} onChange={handleToggle} style={{ marginRight: '10px' }} />
      <span
        style={{
          textDecoration: itemData.isCompleted ? 'line-through' : 'none',
          color: itemData.isCompleted ? '#aaa' : '#213547',
        }}
      >
        {itemData.text}
      </span>
    </div>
  );
};
