// apps/mvvm-solid/src/components/SensorCard.tsx
import { Show } from 'solid-js';
import { A } from '@solidjs/router';
import type { SensorListData } from '@repo/view-models/SensorViewModel';

interface SensorCardProps {
  sensors: SensorListData | null;
}

export default function SensorCard(props: SensorCardProps) {
  return (
    <Show when={props.sensors}>
      {(sensors) => (
        <div class="card">
          <A href="/sensors" class="card-header-link">
            <h3 class="card-title">Sensors</h3>
          </A>
          <p class="card-content">Total: {sensors().length}</p>
        </div>
      )}
    </Show>
  );
}

// apps/mvvm-react-integrated/src/components/SensorCard.tsx
import type { SensorListData } from '@repo/view-models/SensorViewModel';
import React from 'react';
import { Link } from 'react-router-dom';

interface SensorCardProps {
  sensors: SensorListData | null;
}

const SensorCard: React.FC<SensorCardProps> = ({ sensors }) => {
  if (!sensors) return null;
  return (
    <div className="card">
      <Link to="/sensors" className="card-header-link">
        <h3 className="card-title">Sensors</h3>
      </Link>
      <p className="card-content">Total: {sensors.length}</p>
    </div>
  );
};

export default SensorCard;
