// apps/mvvm-react/src/layout/Header.tsx
import { navigationViewModel } from '@repo/shared/view-models/NavigationViewModel';
import { Link } from 'react-router-dom';
import { useSignal } from '../hooks/useSignal';

export const Header = () => {
  const navigation = useSignal(navigationViewModel.navigationList.items$);
  return (
    <header className="header">
      <Link to="/" className="header-item">
        Dashboard
      </Link>
      <nav className="flex-container">
        {navigation.map((item) => (
          <Link key={item.id} to={`/${item.id}`} className="header-item">
            <i className={`icon-${item.icon}`}></i> {item.label}
          </Link>
        ))}
      </nav>
    </header>
  );
};

// apps/mvvm-solid/src/layout/Header.tsx
import { For } from 'solid-js';
import { A } from '@solidjs/router';
import { navigationViewModel } from '@repo/shared/view-models/NavigationViewModel';
import { useSignal } from '../hooks/useSignal';

export function Header() {
  const navigation = useSignal(navigationViewModel.navigationList.items$);

  return (
    <header class="header">
      <A href="/" class="header-item">
        Dashboard
      </A>
      <nav class="flex-container">
        <For each={navigation()}>
          {(item) => (
            <A href={`/${item.id}`} class="header-item">
              <i class={`icon-${item.icon}`}></i> {item.label}
            </A>
          )}
        </For>
      </nav>
    </header>
  );
}
