// packages/create-web-loom/src/templates/solid/js/src/hooks/useObservable.js
import { createSignal, onCleanup } from 'solid-js';

export function useSignalValue(signal) {
  const [value, setValue] = createSignal(signal.get());

  const sync = () => {
    setValue(signal.get());
  };

  sync();
  const unsubscribe = signal.subscribe(sync);
  onCleanup(unsubscribe);

  return value;
}

// apps/mvvm-react-native/src/hooks/useObservable.ts
import { useState, useEffect } from 'react';
import { Observable } from 'rxjs';

export function useObservable<T>(observable: Observable<T>): T | undefined {
  const [value, setValue] = useState<T>();

  useEffect(() => {
    const subscription = observable.subscribe(setValue);
    return () => subscription.unsubscribe();
  }, [observable]);

  return value;
}
