// apps/mvvm-vue/src/components/Dashboard.vue
<template>
  <div class="dashboard-container">
    <h2>Dashboard</h2>

    <div v-if="isLoading" class="loading-message">
      <p>Loading dashboard data...</p>
    </div>

    <div v-if="!isLoading" class="flex-container">
      <div className="flex-item">
        <GreenhouseCard :greenhouseListDataProp="greenHouses" />
      </div>
      <div className="flex-item">
        <SensorCard :sensorListDataProp="sensors" />
      </div>
      <div className="flex-item">
        <ThresholdAlertCard :thresholdAlertsProp="thresholdAlerts" />
      </div>
      <div className="flex-item">
        <SensorReadingCard :sensorReadingsProp="sensorReadings" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, computed } from 'vue';
import { useObservable } from '../hooks/useObservable';

import { greenHouseViewModel } from '@repo/view-models/GreenHouseViewModel';
import { sensorViewModel } from '@repo/view-models/SensorViewModel';
import { sensorReadingViewModel } from '@repo/view-models/SensorReadingViewModel';
import { thresholdAlertViewModel } from '@repo/view-models/ThresholdAlertViewModel';

import GreenhouseCard from './GreenhouseCard.vue';
import SensorCard from './SensorCard.vue';
import SensorReadingCard from './SensorReadingCard.vue';
import ThresholdAlertCard from './ThresholdAlertCard.vue';

const greenHouses = useObservable(greenHouseViewModel.data$, []);
const isLoadingGreenHouses = useObservable(greenHouseViewModel.isLoading$, true);

const sensors = useObservable(sensorViewModel.data$, []);
const isLoadingSensors = useObservable(sensorViewModel.isLoading$, true);

const sensorReadings = useObservable(sensorReadingViewModel.data$, []);
const isLoadingSensorReadings = useObservable(sensorReadingViewModel.isLoading$, true);

const thresholdAlerts = useObservable(thresholdAlertViewModel.data$, []);
const isLoadingThresholdAlerts = useObservable(thresholdAlertViewModel.isLoading$, true);

const isLoading = computed(
  () =>
    isLoadingGreenHouses.value ||
    isLoadingSensors.value ||
    isLoadingSensorReadings.value ||
    isLoadingThresholdAlerts.value,
);

onMounted(async () => {
  try {
    await greenHouseViewModel.fetchCommand.execute();
    await sensorViewModel.fetchCommand.execute();
    await sensorReadingViewModel.fetchCommand.execute();
    await thresholdAlertViewModel.fetchCommand.execute();
  } catch (error) {
    console.error('Error fetching dashboard data:', error);
  }
});
</script>

<style scoped></style>

// apps/mvvm-solid/src/components/Dashboard.tsx
import { Show, createMemo, onMount } from 'solid-js';
import { greenHouseViewModel } from '@repo/view-models/GreenHouseViewModel';
import { sensorViewModel } from '@repo/view-models/SensorViewModel';
import { sensorReadingViewModel } from '@repo/view-models/SensorReadingViewModel';
import { thresholdAlertViewModel } from '@repo/view-models/ThresholdAlertViewModel';
import { useSignal } from '../hooks/useSignal';
import GreenhouseCard from './GreenhouseCard';
import SensorCard from './SensorCard';
import SensorReadingCard from './SensorReadingCard';
import ThresholdAlertCard from './ThresholdAlertCard';

export default function Dashboard() {
  const greenHouses = useSignal(greenHouseViewModel.data$);
  const isLoadingGreenHouses = useSignal(greenHouseViewModel.isLoading$);

  const sensors = useSignal(sensorViewModel.data$);
  const isLoadingSensors = useSignal(sensorViewModel.isLoading$);

  const sensorReadings = useSignal(sensorReadingViewModel.data$);
  const isLoadingSensorReadings = useSignal(sensorReadingViewModel.isLoading$);

  const thresholdAlerts = useSignal(thresholdAlertViewModel.data$);
  const isLoadingThresholdAlerts = useSignal(thresholdAlertViewModel.isLoading$);

  const isLoading = createMemo(
    () =>
      isLoadingGreenHouses() ||
      isLoadingSensors() ||
      isLoadingSensorReadings() ||
      isLoadingThresholdAlerts(),
  );

  onMount(() => {
    void Promise.all([
      greenHouseViewModel.fetchCommand.execute(),
      sensorViewModel.fetchCommand.execute(),
      sensorReadingViewModel.fetchCommand.execute(),
      thresholdAlertViewModel.fetchCommand.execute(),
    ]).catch((error) => {
      console.error('Error fetching data:', error);
    });
  });

  return (
    <div class="dashboard-container">
      <Show when={isLoading()}>
        <p>Loading dashboard data...</p>
      </Show>
      <Show when={!isLoading()}>
        <h2>Dashboard</h2>
        <div class="flex-container">
          <div class="flex-item">
            <GreenhouseCard greenHouses={greenHouses()} />
          </div>
          <div class="flex-item">
            <SensorCard sensors={sensors()} />
          </div>
          <div class="flex-item">
            <ThresholdAlertCard thresholdAlerts={thresholdAlerts() ?? []} />
          </div>
          <div class="flex-item">
            <SensorReadingCard sensorReadings={sensorReadings() ?? []} />
          </div>
        </div>
      </Show>
    </div>
  );
}
