// apps/plugin-react/src/components/GreenhouseCard.tsx
import type { GreenhouseListData } from '@repo/view-models/GreenHouseViewModel';
import React from 'react';
import { Link } from '../router/Routing';

interface GreenhouseCardProps {
  greenHouses: GreenhouseListData | null;
}

const GreenhouseCard: React.FC<GreenhouseCardProps> = ({ greenHouses }) => {
  if (!greenHouses) return null;
  return (
    <div className="card">
      <Link to="/greenhouses" className="card-header-link">
        <h3 className="card-title">Greenhouses</h3>
      </Link>
      <p className="card-content">Total: {greenHouses.length}</p>
    </div>
  );
};

export default GreenhouseCard;

// apps/mvvm-solid/src/components/GreenhouseCard.tsx
import { Show } from 'solid-js';
import { A } from '@solidjs/router';
import type { GreenhouseListData } from '@repo/view-models/GreenHouseViewModel';

interface GreenhouseCardProps {
  greenHouses: GreenhouseListData | null;
}

export default function GreenhouseCard(props: GreenhouseCardProps) {
  return (
    <Show when={props.greenHouses}>
      {(greenHouses) => (
        <div class="card">
          <A href="/greenhouses" class="card-header-link">
            <h3 class="card-title">Greenhouses</h3>
          </A>
          <p class="card-content">Total: {greenHouses().length}</p>
        </div>
      )}
    </Show>
  );
}
