// apps/mvvm-react-integrated/src/components/SensorList.tsx
import { useEffect } from 'react';
import { sensorViewModel } from '@repo/view-models/SensorViewModel';
import { useObservable } from '../hooks/useObservable';
import { Link } from 'react-router-dom';
import BackArrow from '../assets/back-arrow.svg';

export function SensorList() {
  const sensors = useObservable(sensorViewModel.data$, []);

  useEffect(() => {
    const fetchData = async () => {
      await sensorViewModel.fetchCommand.execute();
    };
    fetchData();
  }, []);

  return (
    <>
      <Link to="/" className="back-button">
        <img src={BackArrow} alt="Back to dashboard" style={{ width: '36px', height: '36px' }} />
      </Link>
      <div className="card">
        <h1 className="card-header">Sensors</h1>
        {sensors && sensors.length > 0 ? (
          <ul className="card-body list">
            {sensors.map((sensor) => (
              <li key={sensor.id} className="list-item">
                {sensor.greenhouse.name} {sensor.type} (Status: {sensor.status})
              </li>
            ))}
          </ul>
        ) : (
          <p>No sensors found or still loading...</p>
        )}
      </div>
    </>
  );
}

// apps/mvvm-solid/src/components/SensorList.tsx
import { For, Show, onMount } from 'solid-js';
import { A } from '@solidjs/router';
import { sensorViewModel } from '@repo/view-models/SensorViewModel';
import { useSignal } from '../hooks/useSignal';
import BackArrow from '../assets/back-arrow.svg';

export function SensorList() {
  const sensors = useSignal(sensorViewModel.data$);

  onMount(() => {
    void sensorViewModel.fetchCommand.execute();
  });

  return (
    <>
      <A href="/" class="back-button">
        <img src={BackArrow} alt="Back to dashboard" style={{ width: '36px', height: '36px' }} />
      </A>
      <div class="card">
        <h1 class="card-title">Sensors</h1>
        <Show when={sensors() && sensors()!.length > 0} fallback={<p>No sensors found or still loading...</p>}>
          <ul class="card-content list">
            <For each={sensors() ?? []}>
              {(sensor) => (
                <li class="list-item">
                  {sensor.greenhouse.name} {sensor.type} (Status: {sensor.status})
                </li>
              )}
            </For>
          </ul>
        </Show>
      </div>
    </>
  );
}
