// apps/plugin-react/src/components/SensorReadingCard.tsx
import React, { useEffect, useRef } from 'react';
import { Link } from '../router/Routing';
import {
  Chart,
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  CategoryScale,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import type { SensorReadingListData } from '@repo/view-models/SensorReadingViewModel';

// Register Chart.js components
Chart.register(LineController, LineElement, PointElement, LinearScale, CategoryScale, Title, Tooltip, Legend);

interface SensorReadingCardProps {
  sensorReadings: SensorReadingListData;
}

const SensorReadingCard: React.FC<SensorReadingCardProps> = ({ sensorReadings }) => {
  const chartInstanceRef = useRef<Chart | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    if (sensorReadings.length === 0) {
      if (chartInstanceRef.current) {
        chartInstanceRef.current.destroy();
        chartInstanceRef.current = null;
      }
      return; // Don't render chart if there's no data
    }

    const canvasElement = canvasRef.current;
    if (!canvasElement) {
      console.error('Canvas element not found');
      return;
    }
    const ctx = canvasElement.getContext('2d');
    if (!ctx) {
      console.error('Failed to get canvas context');
      return;
    }

    // Destroy previous chart instance if it exists
    if (chartInstanceRef.current) {
      chartInstanceRef.current.destroy();
    }

    const chartData = {
      labels: sensorReadings.map((reading) => new Date(reading.timestamp).toLocaleTimeString()),
      datasets: [
        {
          label: 'Sensor Value',
          data: sensorReadings.map((reading) => reading.value),
          fill: false,
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1,
        },
      ],
    };

    const chartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        x: {
          title: {
            display: true,
            text: 'Time',
          },
        },
        y: {
          title: {
            display: true,
            text: 'Value',
          },
        },
      },
    };

    // Create new chart instance
    chartInstanceRef.current = new Chart(ctx, {
      type: 'line',
      data: chartData,
      options: chartOptions,
    });

    // Cleanup function to destroy chart on component unmount
    return () => {
      if (chartInstanceRef.current) {
        chartInstanceRef.current.destroy();
        chartInstanceRef.current = null;
      }
    };
  }, [sensorReadings]); // Re-run effect if sensorReadings change

  return (
    <div className="card">
      <Link to="/sensor-readings" className="card-header-link">
        <h3 className="card-title">Sensor Readings</h3>
      </Link>
      <div className="card-content">
        <canvas ref={canvasRef}></canvas>
      </div>
      <p className="card-content">Total Readings: {sensorReadings.length}</p>
    </div>
  );
};

export default SensorReadingCard;

// apps/mvvm-solid/src/components/SensorReadingCard.tsx
import { createEffect, onCleanup } from 'solid-js';
import { A } from '@solidjs/router';
import {
  Chart,
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  CategoryScale,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import type { SensorReadingListData } from '@repo/view-models/SensorReadingViewModel';

Chart.register(LineController, LineElement, PointElement, LinearScale, CategoryScale, Title, Tooltip, Legend);

interface SensorReadingCardProps {
  sensorReadings: SensorReadingListData;
}

export default function SensorReadingCard(props: SensorReadingCardProps) {
  let canvasRef: HTMLCanvasElement | undefined;

  createEffect(() => {
    const readings = props.sensorReadings;
    const canvas = canvasRef;
    if (!canvas) {
      return;
    }

    if (readings.length === 0) {
      return;
    }

    const ctx = canvas.getContext('2d');
    if (!ctx) {
      console.error('Failed to get canvas context');
      return;
    }

    const chart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: readings.map((reading) => new Date(reading.timestamp).toLocaleTimeString()),
        datasets: [
          {
            label: 'Sensor Value',
            data: readings.map((reading) => reading.value),
            fill: false,
            borderColor: 'rgb(75, 192, 192)',
            tension: 0.1,
          },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          x: {
            title: {
              display: true,
              text: 'Time',
            },
          },
          y: {
            title: {
              display: true,
              text: 'Value',
            },
          },
        },
      },
    });

    onCleanup(() => {
      chart.destroy();
    });
  });

  return (
    <div class="card">
      <A href="/sensor-readings" class="card-header-link">
        <h3 class="card-title">Sensor Readings</h3>
      </A>
      <div class="card-content">
        <canvas ref={(el) => (canvasRef = el)} />
      </div>
      <p class="card-content">Total Readings: {props.sensorReadings.length}</p>
    </div>
  );
}
