// apps/mvvm-angular/src/app/layout/header/header.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { navigationViewModel } from '@repo/shared/view-models/NavigationViewModel';

@Component({
  selector: 'app-header',
  imports: [RouterModule, CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent {
  public navigationList$ = navigationViewModel.navigationList.items$;

  constructor() {}
}

<header class="header">
  <a class="header-item" routerLink="/" routerLinkActive="active">Dashboard </a>
  <ul class="flex-container">
    <nav className="flex-container">
      <ng-container *ngIf="navigationList$ | async as navigationList">
        <a class="header-item" *ngFor="let item of navigationList" [routerLink]="['/', item.id]">
          {{ item.label }}
        </a>
      </ng-container>
    </nav>
  </ul>
</header>

// apps/mvvm-react/src/layout/Header.tsx
import { navigationViewModel } from '@repo/shared/view-models/NavigationViewModel';
import { Link } from 'react-router-dom';
import { useSignal } from '../hooks/useSignal';

export const Header = () => {
  const navigation = useSignal(navigationViewModel.navigationList.items$);
  return (
    <header className="header">
      <Link to="/" className="header-item">
        Dashboard
      </Link>
      <nav className="flex-container">
        {navigation.map((item) => (
          <Link key={item.id} to={`/${item.id}`} className="header-item">
            <i className={`icon-${item.icon}`}></i> {item.label}
          </Link>
        ))}
      </nav>
    </header>
  );
};
