// apps/mvvm-vue/src/layout/Header.vue
<template>
  <header class="header">
    <router-link
      to="/"
      class="header-item"
    >
      Dashboard
    </router-link>
    <nav class="flex-container">
      <router-link
        v-for="item in navigationList"
        :key="item.id"
        :to="`/${item.id}`"
        class="header-item"
      >
        {{
          item.label
        }}
      </router-link>
    </nav>
  </header>
</template>

<script setup>
import { computed } from 'vue';
import { useSignal } from '../hooks/useSignal';
import { navigationViewModel } from '@repo/shared/view-models/NavigationViewModel';

const navigation = useSignal(navigationViewModel.navigationList.items$);
const navigationList = computed(() => navigation.value.map((item) => item));
</script>
<style scoped>
a {
  font-weight: 500;
}
</style>

// apps/mvvm-react/src/layout/Header.tsx
import { navigationViewModel } from '@repo/shared/view-models/NavigationViewModel';
import { Link } from 'react-router-dom';
import { useSignal } from '../hooks/useSignal';

export const Header = () => {
  const navigation = useSignal(navigationViewModel.navigationList.items$);
  return (
    <header className="header">
      <Link to="/" className="header-item">
        Dashboard
      </Link>
      <nav className="flex-container">
        {navigation.map((item) => (
          <Link key={item.id} to={`/${item.id}`} className="header-item">
            <i className={`icon-${item.icon}`}></i> {item.label}
          </Link>
        ))}
      </nav>
    </header>
  );
};
